# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='等级名称')),
                ('upgrade_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='升级消费金额')),
                ('team_upgrade_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='团队升级金额')),
                ('commission_rate_lv1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='一级佣金比例')),
                ('commission_rate_lv2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='二级佣金比例')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='会员折扣')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
                'db_table': 'member_level',
                'ordering': ['-sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='关系路径')),
                ('openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信 OpenID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, default='', max_length=500, verbose_name='头像')),
                ('role', models.CharField(choices=[('normal', '普通用户'), ('member', '会员'), ('distributor', '分销商'), ('team_leader', '团队长'), ('city_agent', '城市代理'), ('admin', '平台管理员')], default='normal', max_length=32, verbose_name='角色')),
                ('is_distributor', models.BooleanField(default=False, verbose_name='是否分销商')),
                ('city_agent_level', models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '区县级'), (2, '市级'), (3, '省级')], default=0, verbose_name='城市代理等级')),
                ('city_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='代理区域编码')),
                ('realname', models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名')),
                ('id_card', models.CharField(blank=True, default='', max_length=32, verbose_name='身份证号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='上级')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.memberlevel', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'indexes': [models.Index(fields=['parent'], name='idx_user_parent'), models.Index(fields=['path'], name='idx_user_path'), models.Index(fields=['openid'], name='idx_user_openid'), models.Index(fields=['mobile'], name='idx_user_mobile')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
