# Generated by Django 5.2.16 on 2026-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname_remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Realname Remark'),
        ),
        migrations.AddField(
            model_name='user',
            name='realname_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20, verbose_name='Realname Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='realname_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Realname Verified At'),
        ),
    ]
