# Generated by Django 5.2.16 on 2026-07-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.PositiveSmallIntegerField(verbose_name='代理等级')),
                ('region_code', models.CharField(max_length=20, verbose_name='区域编码')),
                ('region_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='区域抽成比例')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '城市代理',
                'verbose_name_plural': '城市代理',
                'db_table': 'city_agent',
            },
        ),
        migrations.CreateModel(
            name='CityAgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.PositiveSmallIntegerField(verbose_name='代理等级')),
                ('region_code', models.CharField(max_length=20, verbose_name='区域编码')),
                ('region_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='审核备注')),
            ],
            options={
                'verbose_name': '代理申请',
                'verbose_name_plural': '代理申请',
                'db_table': 'city_agent_application',
            },
        ),
    ]
