# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cityagent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_regions', to=settings.AUTH_USER_MODEL, verbose_name='代理用户'),
        ),
        migrations.AddField(
            model_name='cityagentapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddConstraint(
            model_name='cityagent',
            constraint=models.UniqueConstraint(fields=('level', 'region_code'), name='uk_agent_level_region'),
        ),
    ]
