# Generated by Django 5.2.16 on 2026-07-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='菜单编码')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='组件路径')),
                ('permission', models.CharField(blank=True, default='', max_length=100, verbose_name='权限标识')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='层级')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.adminmenu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '后台菜单',
                'verbose_name_plural': '后台菜单',
                'db_table': 'admin_menu',
                'ordering': ['-sort', 'id'],
                'indexes': [models.Index(fields=['parent'], name='idx_admin_menu_parent'), models.Index(fields=['is_show', 'sort'], name='idx_admin_menu_show_sort')],
            },
        ),
    ]
