ADMIN_MENU = [
    {
        "code": "data-center",
        "name": "数据中心",
        "icon": "DataAnalysis",
        "sort": 100,
        "children": [
            {"name": "数据看板", "path": "/dashboard", "permission": "report:dashboard", "sort": 1},
            {"name": "用户趋势", "path": "/reports/users", "permission": "report:users", "sort": 2},
            {"name": "销售报表", "path": "/reports/sales", "permission": "report:sales", "sort": 3},
            {"name": "佣金报表", "path": "/reports/commissions", "permission": "report:commissions", "sort": 4},
            {"name": "营销数据", "path": "/reports/marketing", "permission": "report:marketing", "sort": 5},
        ],
    },
    {
        "code": "product-center",
        "name": "商品中心",
        "icon": "Goods",
        "sort": 90,
        "children": [
            {"name": "商品列表", "path": "/products", "permission": "catalog:product", "sort": 1},
            {"name": "商品分类", "path": "/categories", "permission": "catalog:category", "sort": 2},
            {"name": "SKU 管理", "path": "/products/skus", "permission": "catalog:sku", "sort": 3},
            {"name": "规格模板", "path": "/products/spec-templates", "permission": "catalog:spec_template", "sort": 4},
            {"name": "库存管理", "path": "/products/stocks", "permission": "catalog:stock", "sort": 5},
        ],
    },
    {
        "code": "order-service",
        "name": "订单售后",
        "icon": "Tickets",
        "sort": 80,
        "children": [
            {"name": "订单列表", "path": "/orders", "permission": "orders:order", "sort": 1},
            {"name": "售后管理", "path": "/orders/aftersales", "permission": "orders:aftersale", "sort": 2},
            {"name": "退款管理", "path": "/refunds", "permission": "orders:refund", "sort": 3},
            {"name": "发票管理", "path": "/invoices", "permission": "orders:invoice", "sort": 4},
            {"name": "订单统计", "path": "/orders/statistics", "permission": "orders:statistics", "sort": 5},
        ],
    },
    {
        "code": "user-member",
        "name": "用户会员",
        "icon": "User",
        "sort": 70,
        "children": [
            {"name": "用户列表", "path": "/users", "permission": "users:user", "sort": 1},
            {"name": "会员等级", "path": "/users/levels", "permission": "users:level", "sort": 2},
            {"name": "实名认证审核", "path": "/realname", "permission": "users:realname", "sort": 3},
            {"name": "分销关系", "path": "/users/distribution-relations", "permission": "users:relation", "sort": 4},
        ],
    },
    {
        "code": "distribution-team",
        "name": "分销团队",
        "icon": "Share",
        "sort": 60,
        "children": [
            {"name": "分销配置", "path": "/distribution/config", "permission": "distribution:config", "sort": 1},
            {"name": "佣金明细", "path": "/distribution/commissions", "permission": "distribution:commission", "sort": 2},
            {"name": "团队管理", "path": "/distribution/teams", "permission": "distribution:team", "sort": 3},
            {"name": "分销统计", "path": "/distribution/statistics", "permission": "distribution:statistics", "sort": 4},
        ],
    },
    {
        "code": "city-agent",
        "name": "城市代理",
        "icon": "Location",
        "sort": 50,
        "children": [
            {"name": "代理申请审核", "path": "/agents/applications", "permission": "agents:application", "sort": 1},
            {"name": "代理列表", "path": "/agents", "permission": "agents:agent", "sort": 2},
            {"name": "区域业绩", "path": "/agents/performance", "permission": "agents:performance", "sort": 3},
            {"name": "代理佣金", "path": "/agents/commissions", "permission": "agents:commission", "sort": 4},
        ],
    },
    {
        "code": "reward-pool",
        "name": "奖金池",
        "icon": "Trophy",
        "sort": 40,
        "children": [
            {"name": "池子管理", "path": "/rewards", "permission": "rewards:pool", "sort": 1},
            {"name": "权重配置", "path": "/rewards/rules", "permission": "rewards:rule", "sort": 2},
            {"name": "分配记录", "path": "/rewards/records", "permission": "rewards:record", "sort": 3},
            {"name": "模拟测算", "path": "/rewards/simulator", "permission": "rewards:simulator", "sort": 4},
        ],
    },
    {
        "code": "marketing-center",
        "name": "营销中心",
        "icon": "Present",
        "sort": 30,
        "children": [
            {"name": "优惠券模板", "path": "/marketing/coupons", "permission": "marketing:coupon", "sort": 1},
            {"name": "团购活动", "path": "/marketing/groups", "permission": "marketing:group", "sort": 2},
            {"name": "秒杀活动", "path": "/marketing/seckills", "permission": "marketing:seckill", "sort": 3},
        ],
    },
    {
        "code": "finance-settlement",
        "name": "财务结算",
        "icon": "Wallet",
        "sort": 20,
        "children": [
            {"name": "提现审核", "path": "/finance/withdrawals", "permission": "finance:withdrawal", "sort": 1},
            {"name": "资金流水", "path": "/finance/flows", "permission": "finance:flow", "sort": 2},
            {"name": "平台收支", "path": "/finance/income-expense", "permission": "finance:summary", "sort": 3},
            {"name": "税务报表", "path": "/finance/tax-reports", "permission": "finance:tax", "sort": 4},
        ],
    },
    {
        "code": "permission-system",
        "name": "权限系统",
        "icon": "Lock",
        "sort": 10,
        "children": [
            {"name": "管理员管理", "path": "/system/admins", "permission": "system:admin", "sort": 1},
            {"name": "角色管理", "path": "/system/roles", "permission": "system:role", "sort": 2},
            {"name": "菜单管理", "path": "/system/menus", "permission": "system:menu", "sort": 3},
            {"name": "操作日志", "path": "/system/logs", "permission": "system:log", "sort": 4},
        ],
    },
]
