# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待发货'), ('pending_receipt', '待收货'), ('completed', '已完成'), ('refunding', '售后中'), ('closed', '已关闭')], default='pending_payment', max_length=32, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='商品总额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='优惠金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实付金额')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_title', models.CharField(max_length=200, verbose_name='商品标题快照')),
                ('sku_code', models.CharField(max_length=64, verbose_name='SKU 编码快照')),
                ('spec_json', models.JSONField(blank=True, default=dict, verbose_name='规格快照')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('selected', models.BooleanField(default=True, verbose_name='是否选中')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart_item',
            },
        ),
    ]
