# Generated by Django 5.2.16 on 2026-07-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment_no', models.CharField(max_length=128, unique=True, verbose_name='Payment No')),
                ('channel', models.CharField(choices=[('mock', 'Mock'), ('wechat', 'WeChat')], default='mock', max_length=20, verbose_name='Channel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(verbose_name='Paid At')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw Payload')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Record',
                'db_table': 'payment_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='idx_payment_order_status'), models.Index(fields=['payment_no'], name='idx_payment_no')],
            },
        ),
    ]
