# Generated by Django 5.2.16 on 2026-07-20 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address Detail'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Receiver Mobile'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Receiver Name'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='gateway_trade_no',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Gateway Trade No'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待发货'), ('pending_receipt', '待收货'), ('completed', '已完成'), ('refunding', '售后中'), ('refunded', '已退款'), ('closed', '已关闭')], default='pending_payment', max_length=32, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='channel',
            field=models.CharField(choices=[('mock', 'Mock'), ('wechat', 'WeChat'), ('balance', 'Balance')], default='mock', max_length=20, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid At'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='InvoiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('invoice_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=20, verbose_name='Invoice Type')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('tax_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Tax No')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('content', models.CharField(blank=True, default='商品明细', max_length=100, verbose_name='Content')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='Audit Remark')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Issued At')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Invoice Application',
                'verbose_name_plural': 'Invoice Application',
                'db_table': 'invoice_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_invoice_user_status')],
            },
        ),
        migrations.CreateModel(
            name='LogisticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='Company')),
                ('tracking_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Tracking No')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('traces', models.JSONField(blank=True, default=list, verbose_name='Traces')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw Payload')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='logistics', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Logistics Record',
                'verbose_name_plural': 'Logistics Record',
                'db_table': 'logistics_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_no'], name='idx_logistics_tracking')],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='Receiver Name')),
                ('receiver_mobile', models.CharField(max_length=20, verbose_name='Receiver Mobile')),
                ('province', models.CharField(blank=True, default='', max_length=50, verbose_name='Province')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='City')),
                ('district', models.CharField(blank=True, default='', max_length=50, verbose_name='District')),
                ('address_detail', models.CharField(max_length=255, verbose_name='Address Detail')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order Address',
                'verbose_name_plural': 'Order Address',
                'db_table': 'order_address',
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='idx_addr_user_default')],
            },
        ),
        migrations.CreateModel(
            name='RefundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('refund_no', models.CharField(max_length=64, unique=True, verbose_name='Refund No')),
                ('refund_type', models.CharField(choices=[('refund_only', 'Refund Only'), ('return_and_refund', 'Return And Refund')], default='refund_only', max_length=30, verbose_name='Refund Type')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='Audit Remark')),
                ('gateway_refund_no', models.CharField(blank=True, default='', max_length=128, verbose_name='Gateway Refund No')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Requested At')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Refunded At')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw Payload')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_applications', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_applications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Refund Application',
                'verbose_name_plural': 'Refund Application',
                'db_table': 'refund_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='idx_refund_order_status'), models.Index(fields=['user', 'status'], name='idx_refund_user_status'), models.Index(fields=['refund_no'], name='idx_refund_no')],
            },
        ),
    ]
