# Generated by Django 5.2.16 on 2026-07-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardDistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='分配得分')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='分配金额')),
                ('status', models.CharField(choices=[('pending', '待发放'), ('paid', '已发放'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('distributed_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
            ],
            options={
                'verbose_name': '奖金池分配记录',
                'verbose_name_plural': '奖金池分配记录',
                'db_table': 'reward_distribution_record',
            },
        ),
        migrations.CreateModel(
            name='RewardPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='池子名称')),
                ('pool_type', models.CharField(choices=[('global', '平台全局池'), ('city_agent', '城市代理池'), ('team_leader', '团队长池'), ('distributor', '分销精英池'), ('monthly', '月度争霸池')], max_length=32, verbose_name='池子类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='池子金额')),
                ('min_performance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最低业绩门槛')),
                ('max_user_ratio', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='单用户最高占比')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '奖金池',
                'verbose_name_plural': '奖金池',
                'db_table': 'reward_pool',
            },
        ),
        migrations.CreateModel(
            name='RewardPoolRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('team_amount_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='团队业绩权重')),
                ('team_count_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='团队人数权重')),
                ('personal_amount_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='个人业绩权重')),
                ('rank_config', models.JSONField(blank=True, default=dict, verbose_name='排名阶梯配置')),
            ],
            options={
                'verbose_name': '奖金池规则',
                'verbose_name_plural': '奖金池规则',
                'db_table': 'reward_pool_rule',
            },
        ),
    ]
