# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarddistributionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='受益用户'),
        ),
        migrations.AddField(
            model_name='rewarddistributionrecord',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='rewards.rewardpool', verbose_name='奖金池'),
        ),
        migrations.AddField(
            model_name='rewardpoolrule',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rewards.rewardpool', verbose_name='奖金池'),
        ),
        migrations.AddIndex(
            model_name='rewarddistributionrecord',
            index=models.Index(fields=['pool', 'status'], name='idx_reward_pool_status'),
        ),
        migrations.AddIndex(
            model_name='rewarddistributionrecord',
            index=models.Index(fields=['user', 'status'], name='idx_reward_user_status'),
        ),
    ]
