# Generated by Django 5.2.16 on 2026-07-18 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frozen Balance')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Income')),
                ('total_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Withdraw')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallet',
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='FundFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flow_type', models.CharField(choices=[('income', 'Income'), ('withdraw', 'Withdraw'), ('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('adjust', 'Adjust')], max_length=20, verbose_name='Flow Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance After')),
                ('biz_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Biz Type')),
                ('biz_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Biz ID')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='Remark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='finance.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Fund Flow',
                'verbose_name_plural': 'Fund Flow',
                'db_table': 'fund_flow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'flow_type'], name='idx_fund_user_type'), models.Index(fields=['biz_type', 'biz_id'], name='idx_fund_biz')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('account_no', models.CharField(max_length=100, verbose_name='Account No')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='Audit Remark')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='Audited At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdraw Application',
                'verbose_name_plural': 'Withdraw Application',
                'db_table': 'withdraw_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='idx_withdraw_user_status')],
            },
        ),
    ]
