# Generated by Django 5.2.16 on 2026-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawapplication',
            name='channel',
            field=models.CharField(choices=[('manual', 'Manual'), ('wechat', 'WeChat'), ('bank', 'Bank')], default='manual', max_length=20, verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='withdrawapplication',
            name='payout_no',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Payout No'),
        ),
        migrations.AddField(
            model_name='withdrawapplication',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw Payload'),
        ),
        migrations.AlterField(
            model_name='withdrawapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paying', 'Paying'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
