# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('sub_title', models.CharField(blank=True, default='', max_length=255, verbose_name='副标题')),
                ('cover', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图')),
                ('detail', models.TextField(blank=True, default='', verbose_name='商品详情')),
                ('sale_status', models.CharField(choices=[('draft', '草稿'), ('on_sale', '上架'), ('off_sale', '下架')], default='draft', max_length=20, verbose_name='销售状态')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='展示价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='划线价')),
                ('total_stock', models.IntegerField(default=0, verbose_name='总库存')),
                ('is_distribution', models.BooleanField(default=True, verbose_name='是否参与分销')),
                ('commission_type', models.CharField(blank=True, default='', max_length=20, verbose_name='佣金类型')),
                ('commission_rate_lv1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='一级佣金比例')),
                ('commission_rate_lv2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='二级佣金比例')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('spec_names', models.JSONField(blank=True, default=list, verbose_name='规格维度')),
            ],
            options={
                'verbose_name': '规格模板',
                'verbose_name_plural': '规格模板',
                'db_table': 'spec_template',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('icon', models.URLField(blank=True, default='', max_length=500, verbose_name='分类图标')),
                ('banner', models.URLField(blank=True, default='', max_length=500, verbose_name='分类横幅')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='层级')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='层级路径')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_distribution', models.BooleanField(default=True, verbose_name='是否参与分销')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200, verbose_name='SEO 标题')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO 关键词')),
                ('seo_description', models.CharField(blank=True, default='', max_length=500, verbose_name='SEO 描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.productcategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'product_category',
                'ordering': ['-sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=True, verbose_name='是否主分类')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategory', verbose_name='分类')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品分类关联',
                'verbose_name_plural': '商品分类关联',
                'db_table': 'product_category_relation',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='catalog.ProductCategoryRelation', to='catalog.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sku_code', models.CharField(max_length=64, unique=True, verbose_name='SKU 编码')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='规格快照')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='售价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='划线价')),
                ('stock', models.IntegerField(default=0, verbose_name='可售库存')),
                ('locked_stock', models.IntegerField(default=0, verbose_name='锁定库存')),
                ('warning_stock', models.IntegerField(default=0, verbose_name='预警库存')),
                ('image', models.URLField(blank=True, default='', max_length=500, verbose_name='SKU 图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='catalog.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品 SKU',
                'verbose_name_plural': '商品 SKU',
                'db_table': 'product_sku',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('change_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('lock', '锁定'), ('unlock', '解锁'), ('rollback', '回滚')], max_length=20, verbose_name='变更类型')),
                ('quantity', models.IntegerField(verbose_name='变更数量')),
                ('before_stock', models.IntegerField(verbose_name='变更前库存')),
                ('after_stock', models.IntegerField(verbose_name='变更后库存')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='catalog.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '库存变更日志',
                'verbose_name_plural': '库存变更日志',
                'db_table': 'stock_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['path'], name='idx_category_path'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_show', 'sort'], name='idx_category_show_sort'),
        ),
        migrations.AddConstraint(
            model_name='productcategoryrelation',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='uk_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_status'], name='idx_product_sale_status'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_distribution'], name='idx_product_distribution'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product'], name='idx_sku_product'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sku_code'], name='idx_sku_code'),
        ),
    ]
