# Generated by Django 5.2.16 on 2026-07-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '一级佣金'), (2, '二级佣金')], verbose_name='分销层级')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='佣金比例')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='佣金金额')),
                ('status', models.CharField(choices=[('frozen', '冻结中'), ('settled', '已结算'), ('canceled', '已取消')], default='frozen', max_length=20, verbose_name='状态')),
                ('settle_at', models.DateTimeField(blank=True, null=True, verbose_name='预计结算时间')),
            ],
            options={
                'verbose_name': '佣金明细',
                'verbose_name_plural': '佣金明细',
                'db_table': 'commission_record',
            },
        ),
        migrations.CreateModel(
            name='DistributionConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='平台默认配置', max_length=100, verbose_name='配置名称')),
                ('default_rate_lv1', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='默认一级佣金比例')),
                ('default_rate_lv2', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='默认二级佣金比例')),
                ('settlement_delay_days', models.PositiveIntegerField(default=7, verbose_name='冻结期天数')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '分销配置',
                'verbose_name_plural': '分销配置',
                'db_table': 'distribution_config',
            },
        ),
    ]
