# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeamStat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('team_count', models.PositiveIntegerField(default=0, verbose_name='团队总人数')),
                ('direct_count', models.PositiveIntegerField(default=0, verbose_name='直推人数')),
                ('indirect_count', models.PositiveIntegerField(default=0, verbose_name='间推人数')),
                ('team_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='团队订单总额')),
                ('team_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='团队佣金总额')),
            ],
            options={
                'verbose_name': '团队统计',
                'verbose_name_plural': '团队统计',
                'db_table': 'user_team_stat',
            },
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='orders.order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_commissions', to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='受益用户'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['user', 'status'], name='idx_commission_user_status'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['order'], name='idx_commission_order'),
        ),
    ]
