# Generated by Django 5.2.16 on 2026-07-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('coupon_type', models.CharField(choices=[('full_reduction', '满减券'), ('discount', '折扣券'), ('new_user', '新人券'), ('product', '指定商品券'), ('category', '指定分类券')], max_length=32, verbose_name='优惠券类型')),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='使用门槛')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='优惠金额')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='折扣比例')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='发行数量')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='每人限领')),
                ('started_at', models.DateTimeField(verbose_name='领取开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='领取结束时间')),
                ('valid_days', models.PositiveIntegerField(default=7, verbose_name='领取后有效天数')),
                ('categories', models.ManyToManyField(blank=True, to='catalog.productcategory', verbose_name='适用分类')),
                ('products', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='适用商品')),
            ],
            options={
                'verbose_name': '优惠券模板',
                'verbose_name_plural': '优惠券模板',
                'db_table': 'coupon_template',
            },
        ),
        migrations.CreateModel(
            name='GroupBuyingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='团购名称')),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='团购价')),
                ('min_members', models.PositiveIntegerField(default=2, verbose_name='成团人数')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='团购库存')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='结束时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productsku', verbose_name='团购 SKU')),
            ],
            options={
                'verbose_name': '团购活动',
                'verbose_name_plural': '团购活动',
                'db_table': 'group_buying_activity',
            },
        ),
        migrations.CreateModel(
            name='SeckillActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='秒杀名称')),
                ('seckill_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='秒杀价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='秒杀库存')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='每人限购')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(verbose_name='结束时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productsku', verbose_name='秒杀 SKU')),
            ],
            options={
                'verbose_name': '秒杀活动',
                'verbose_name_plural': '秒杀活动',
                'db_table': 'seckill_activity',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('valid_from', models.DateTimeField(verbose_name='有效开始时间')),
                ('valid_to', models.DateTimeField(verbose_name='有效结束时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.coupontemplate', verbose_name='优惠券模板')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupon',
            },
        ),
    ]
