# Generated by Django 5.2.16 on 2026-07-18 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_initial'),
        ('orders', '0003_paymentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity_type', models.CharField(choices=[('group', 'Group'), ('seckill', 'Seckill')], max_length=20, verbose_name='Activity Type')),
                ('activity_id', models.PositiveBigIntegerField(verbose_name='Activity ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Purchase Record',
                'verbose_name_plural': 'Activity Purchase Record',
                'db_table': 'activity_purchase_record',
                'indexes': [models.Index(fields=['user', 'activity_type', 'activity_id'], name='idx_activity_user'), models.Index(fields=['activity_type', 'activity_id'], name='idx_activity_lookup')],
            },
        ),
    ]
